services:
  pikaraoke:
    image: pikaraoke:latest
    container_name: PiKaraoke
    network_mode: host
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - pikaraoke-songs:/pikaraoke-songs
    restart: unless-stopped